# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('images_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
