# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Do not add too large pics, please', upload_to='uploads'),
        ),
    ]
